# Generated by Django 5.1.6 on 2025-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nuts', models.BooleanField()),
                ('image', models.URLField()),
                ('vegeterian', models.BooleanField()),
                ('spiciness', models.IntegerField()),
                ('categoryId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
