# Generated by Django 5.1.6 on 2025-03-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dish_delete_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
    ]
